/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author helia
 */
public class Frame_Defaite extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame_Defaite.class.getName());
    private int nbCasesRevelees;
    int nbTotalCases;

    public Frame_Defaite(int nbCasesRevelees, int nbTotalCases) {
        this.nbCasesRevelees = nbCasesRevelees;
        this.nbTotalCases = nbTotalCases;
        initComponents();
        texte_stats.setText("Vous avez révélé " + nbCasesRevelees + " case(s) sur " + nbTotalCases + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextePerdu = new javax.swing.JLabel();
        Btn_Recommencer = new javax.swing.JButton();
        texte_stats = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextePerdu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextePerdu.setText("<HTML> BOOOOOOOOOM !!! Vous avez perdu !! <HMTL>");

        Btn_Recommencer.setText("Recommencer");
        Btn_Recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RecommencerActionPerformed(evt);
            }
        });

        texte_stats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_stats.setText("Vous avez révelé ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Recommencer)
                            .addComponent(TextePerdu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(texte_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(TextePerdu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texte_stats)
                .addGap(36, 36, 36)
                .addComponent(Btn_Recommencer)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_RecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RecommencerActionPerformed
        Frame_Accueil accueil = new Frame_Accueil();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_RecommencerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Recommencer;
    private javax.swing.JLabel TextePerdu;
    private javax.swing.JLabel texte_stats;
    // End of variables declaration//GEN-END:variables
}
