
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author helia
 */
public class Frame_Accueil extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame_Accueil.class.getName());

    /**
     * Creates new form Frame_Accueil
     */
    public Frame_Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nbColonnes = new javax.swing.JLabel();
        lbl_nbLignes = new javax.swing.JLabel();
        lbl_nbBombes = new javax.swing.JLabel();
        lbl_nbVies = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nb_colonnes = new javax.swing.JSpinner();
        nb_lignes = new javax.swing.JSpinner();
        nb_bombes = new javax.swing.JSpinner();
        nb_vies = new javax.swing.JSpinner();
        btn_Entrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        lbl_nbColonnes.setText("Nombres de Colonnes");
        jPanel1.add(lbl_nbColonnes);

        lbl_nbLignes.setText("Nombres de Lignes");
        jPanel1.add(lbl_nbLignes);

        lbl_nbBombes.setText("Nombre de Bombes");
        jPanel1.add(lbl_nbBombes);

        lbl_nbVies.setText("Nombres de Vies");
        jPanel1.add(lbl_nbVies);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 10));
        jPanel2.add(nb_colonnes);
        jPanel2.add(nb_lignes);
        jPanel2.add(nb_bombes);
        jPanel2.add(nb_vies);

        btn_Entrer.setText("Entrer");
        btn_Entrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Entrer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Entrer)
                        .addGap(155, 155, 155))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrerActionPerformed
        int nbColonnes = (Integer) nb_colonnes.getValue();
        int nbLignes = (Integer) nb_lignes.getValue();
        int nbBombes = (Integer) nb_bombes.getValue();
        int nbVies = (Integer) nb_vies.getValue();
        if (nbLignes <= 0 || nbColonnes <= 0 || nbLignes <= 0 || nbVies<=0) {
            JOptionPane.showConfirmDialog(
                    this,
                    "Veuillez choisir une valeur minimale de 1 ",
                    "Erreur de configuration",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (nbBombes <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Il faut au moins 1 bombe",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
            if (nbBombes == nbVies) {
            JOptionPane.showMessageDialog(
                    this,
                    "Il faut plus de bombes que de vie",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (nbBombes > nbLignes * nbColonnes) {
            JOptionPane.showMessageDialog(
                    this,
                    "Vous avez choisis plus de bombes que de cases",
                    "Erreur de configuration",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Super_Demineur jeu = new Super_Demineur(nbColonnes, nbLignes, nbBombes, nbVies);
        jeu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EntrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame_Accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_nbBombes;
    private javax.swing.JLabel lbl_nbColonnes;
    private javax.swing.JLabel lbl_nbLignes;
    private javax.swing.JLabel lbl_nbVies;
    private javax.swing.JSpinner nb_bombes;
    private javax.swing.JSpinner nb_colonnes;
    private javax.swing.JSpinner nb_lignes;
    private javax.swing.JSpinner nb_vies;
    // End of variables declaration//GEN-END:variables
}
