/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author helia
 */
import javax.swing.JButton;

public class Super_Demineur extends javax.swing.JFrame {

    private Partie Jeu;
    private int colonnes;
    private int lignes;
    private int bombes;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Super_Demineur.class.getName());

    /**
     * Creates new form Super_Demineur
     */
    public Super_Demineur(int colonnes, int lignes, int bombes) {
         this.colonnes = colonnes;
        this.lignes = lignes;
        this.bombes = bombes;
        Jeu = new Partie();
        initComponents();       
        Jeu.initaliserPartie(this.lignes, this.colonnes, this.bombes);
        Jeu.demarrerPartie();
        PanneauGrille.removeAll();
        PanneauGrille.setLayout(new java.awt.GridLayout(this.lignes, this.colonnes));
        for (int i = 0; i < this.lignes; i++) {
            for (int j = 0; j < this.colonnes; j++) {
                final int x = i;
                final int y = j;
                CelluleGraphique bouton_cellule = new CelluleGraphique(Jeu.getGrille().getCellule(i, j), 36, 36);
                ActionListener ecouteurClick = new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (Jeu.isPartieTerminee()) {
                        return;
                    }
                        ((CelluleGraphique) e.getSource()).setEnabled(false);
                        Jeu.tourDeJeu(x,y);
                        repaint();
                        if (Jeu.isPartieTerminee()) {
                    for (java.awt.Component c : PanneauGrille.getComponents()) {
                        c.setEnabled(false);
                    }
                        }            
                    }
                };
                bouton_cellule.addActionListener(ecouteurClick);
                PanneauGrille.add(bouton_cellule);
            }
        }
        PanneauGrille.revalidate();
        PanneauGrille.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 51, 51));
        PanneauGrille.setLayout(new java.awt.GridLayout(10, 10));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 65, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
